### PR TITLE
Support for Multiwinner

### PR DESCRIPTION
**Pull request by subdigital**
- adds optional `count` property to placement requests
- decisions are now an array of results
- response tries a single value first, falls back to array for decoding

### CODE REVIEW

**Comment by subdigital** [comment]
Resolves #18

**Comment by karnowski** [comment]
@subdigital It's not clear to me, but if the `count` is NOT specified, will this code just ignore `count` on the request?  (That's what we want.)  I just want to make sure that we do NOT send either a `nil` or a `1` by default.   (Long story, but having any value for `count` at all triggers different behavior than when it's missing.)

**Comment by subdigital** [comment]
Verifying this.... we may need to implement a custom `encode` method here to avoid if the value is nil.

**Comment by subdigital** [comment]
Confirmed, the default behavior is _not_ to include the key at all if the `count` is nil. We're good.

**Review by karnowski — APPROVED** [review]
🏆

**Pull request merged**
