### PR TITLE
Support for recording impressions

### PR DESCRIPTION
**Pull request by subdigital**

### CODE REVIEW

**Comment by subdigital** [comment]
Dependent on #25

**Comment by karnowski** [comment]
@subdigital This will still send the `X-Adzerk-Sdk-Version` header, right?  We still want it to report `adzerk-decision-sdk-ios:[version]`.

**Comment by karnowski** [comment]
To be clear -- as long as the header is sent, then I approve this PR!

**Comment by subdigital** [comment]
After looking at this again, should this be on userDB instead? We already have a (private) method for sending a fire-and-forget pixel request...

**Comment by karnowski** [comment]
No, impression pixels are not associated with UserDB.

**Comment by subdigital** [comment]
> @subdigital This will still send the `X-Adzerk-Sdk-Version` header, right? We still want it to report `adzerk-decision-sdk-ios:[version]`.

I had forgotten to bring this over, but it's there now. All requests will have this.

**Comment by subdigital** [comment]
image

**Pull request merged**
